@startuml

allow_mixing

actor Citoyen

object Portefeuille
object PES_RegistreQuebec
object PES_CurateurPublic
object ACAG_PY_Agency
object ACA_PY_Issuer
object ACA_PY_Verifier
object AGENT_Mediateur
database Blockchain

Citoyen -down-> Portefeuille
Citoyen -down-> PES_CurateurPublic
Citoyen -down-> PES_RegistreQuebec
Portefeuille -down-> PES_RegistreQuebec
Portefeuille -down-> PES_CurateurPublic
Portefeuille <-down-> AGENT_Mediateur
PES_CurateurPublic <-down-> ACAG_PY_Agency
ACAG_PY_Agency <-down-> ACA_PY_Verifier
PES_RegistreQuebec <-down-> ACAG_PY_Agency
ACAG_PY_Agency <-down-> ACA_PY_Issuer

ACA_PY_Issuer <-down-> Blockchain
ACA_PY_Verifier <-down-> Blockchain
Portefeuille <-down-> Blockchain

AGENT_Mediateur <-down-> ACA_PY_Verifier
AGENT_Mediateur <-down-> ACA_PY_Issuer

@enduml
